import unittest
from typing import List, Optional, Dict, Any
import asyncio

from fastapi import HTTPException
from fastapi.testclient import TestClient

from src.core.models import Item
from src.core.storage_interface import StorageInterface
from src.api import routes # This is where 'app' and 'storage_adapter' are defined

# MockStorage implementation as provided in the prompt
class MockStorage(StorageInterface):
    def __init__(self):
        self.data: Dict[str, Dict[str, Any]] = {}
        self.counter: int = 0

    async def create(self, item_data: Dict[str, Any]) -> Dict[str, Any]:
        self.counter += 1
        new_id = item_data.get("id") # Pydantic model might not have 'id' in initial payload
        if not new_id: # If id is not in item_data (e.g. when Item model generates it or it's excluded)
            new_id = str(self.counter)

        # The Item model in routes.py expects 'id' to be set by storage if not present
        # Our storage adapter should ensure 'id' is part of the returned dict.
        final_item_data = item_data.copy() # Avoid modifying input
        final_item_data["id"] = new_id
        self.data[new_id] = final_item_data
        return final_item_data

    async def read_all(self) -> List[Dict[str, Any]]:
        return list(self.data.values())

    async def read_one(self, item_id: str) -> Optional[Dict[str, Any]]:
        return self.data.get(item_id)

    async def update(self, item_id: str, item_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        if item_id in self.data:
            # Ensure 'id' in the payload doesn't change the key 'item_id'
            # The item_data for update might not contain 'id', or it might.
            # The storage should ensure the item_id of the record is preserved.
            updated_record = self.data[item_id].copy() # take a copy to update
            updated_record.update(item_data) # apply changes
            updated_record["id"] = item_id # ensure id is not changed by payload
            self.data[item_id] = updated_record
            return updated_record
        return None

    async def delete(self, item_id: str) -> bool:
        if item_id in self.data:
            del self.data[item_id]
            return True
        return False

class TestApiRoutes(unittest.TestCase):

    def setUp(self):
        self.mock_storage = MockStorage()
        # Override the actual storage adapter in routes module with our mock
        routes.storage_adapter = self.mock_storage
        self.client = TestClient(routes.app)

    def test_create_item_api(self):
        item_payload = {"name": "API Test Item", "description": "Testing via API", "data": {"api_key": "api_val"}}
        response = self.client.post("/items", json=item_payload)
        self.assertEqual(response.status_code, 200) # Default FastAPI is 200 for POST

        response_data = response.json()
        self.assertIsNotNone(response_data.get("id")) # ID should be generated by mock storage
        self.assertEqual(response_data["name"], item_payload["name"])
        self.assertEqual(response_data["description"], item_payload["description"])
        self.assertEqual(response_data["data"], item_payload["data"])

        # Check if item was actually "created" in mock storage
        # The ID is generated by MockStorage, so we use the one from response
        created_id = response_data["id"]
        # Need to run async code in a sync test method
        stored_item = asyncio.run(self.mock_storage.read_one(created_id))
        self.assertIsNotNone(stored_item)
        self.assertEqual(stored_item["name"], item_payload["name"])

    def test_read_items_api(self):
        # Pre-populate mock storage
        item1_data = {"id": "item1", "name": "API Item 1", "description": "Desc 1", "data": {}}
        item2_data = {"id": "item2", "name": "API Item 2", "description": "Desc 2", "data": {}}
        asyncio.run(self.mock_storage.create(item1_data))
        asyncio.run(self.mock_storage.create(item2_data))

        response = self.client.get("/items")
        self.assertEqual(response.status_code, 200)
        response_data = response.json()
        self.assertEqual(len(response_data), 2)
        self.assertTrue(any(item['name'] == item1_data['name'] for item in response_data))
        self.assertTrue(any(item['name'] == item2_data['name'] for item in response_data))

    def test_read_one_item_api(self):
        item_data = {"id": "specific_api_item", "name": "Specific API Item", "data": {}}
        asyncio.run(self.mock_storage.create(item_data))

        response = self.client.get(f"/items/{item_data['id']}")
        self.assertEqual(response.status_code, 200)
        response_data = response.json()
        self.assertEqual(response_data["name"], item_data["name"])
        self.assertEqual(response_data["id"], item_data["id"])

    def test_read_one_item_not_found_api(self):
        response = self.client.get("/items/nonexistent-api-item")
        self.assertEqual(response.status_code, 404)
        self.assertEqual(response.json()["detail"], "Item not found")

    def test_update_item_api(self):
        original_item_data = {"id": "update_me", "name": "Original API Name", "description": "Original", "data": {"k": "v"}}
        asyncio.run(self.mock_storage.create(original_item_data))

        update_payload = {"name": "Updated API Name", "description": "Updated Desc", "data": {"new_k": "new_v"}}
        response = self.client.put(f"/items/{original_item_data['id']}", json=update_payload)
        self.assertEqual(response.status_code, 200)

        response_data = response.json()
        self.assertEqual(response_data["id"], original_item_data["id"]) # ID should not change
        self.assertEqual(response_data["name"], update_payload["name"])
        self.assertEqual(response_data["description"], update_payload["description"])
        self.assertEqual(response_data["data"], update_payload["data"])

        # Verify in mock storage
        updated_stored_item = asyncio.run(self.mock_storage.read_one(original_item_data['id']))
        self.assertEqual(updated_stored_item["name"], update_payload["name"])


    def test_update_item_not_found_api(self):
        update_payload = {"name": "Update Nonexistent", "data": {}}
        response = self.client.put("/items/nonexistent-api-update", json=update_payload)
        self.assertEqual(response.status_code, 404)
        self.assertEqual(response.json()["detail"], "Item not found")

    def test_delete_item_api(self):
        item_to_delete = {"id": "delete_me_api", "name": "API Item to Delete", "data": {}}
        asyncio.run(self.mock_storage.create(item_to_delete))

        response = self.client.delete(f"/items/{item_to_delete['id']}")
        self.assertEqual(response.status_code, 204) # As per current routes.py

        # Verify it's deleted from mock storage
        self.assertIsNone(asyncio.run(self.mock_storage.read_one(item_to_delete['id'])))

    def test_delete_item_not_found_api(self):
        response = self.client.delete("/items/nonexistent-api-delete")
        self.assertEqual(response.status_code, 404)
        self.assertEqual(response.json()["detail"], "Item not found")

if __name__ == '__main__':
    unittest.main()
