[DEFAULT]
# Supported adapters: memory, csv, database, redis, mysql
ADAPTER_TYPE = memory

[csv]
filepath = data/items_config.csv
fieldnames = id,name,description,data

[database]
# For SQLite
db_url = sqlite:///./data/items_config.db

[redis]
redis_url = redis://localhost:6379/0

[mysql]
# SQLAlchemy URL for MySQL. Ensure the database specified in the URL exists.
# The application will attempt to create tables, but not the database itself.
# Format: mysql+pymysql://USER:PASSWORD@HOST:PORT/DATABASE_NAME
# Example: db_url = mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase
db_url = mysql+pymysql://user:password@host:port/database
