[DEFAULT]
# Supported adapters: memory, csv, database, redis
ADAPTER_TYPE = memory

[csv]
filepath = data/items_config.csv
fieldnames = id,name,description,data

[database]
db_url = sqlite:///./data/items_config.db

[redis]
redis_url = redis://localhost:6379/0
