from typing import List, Optional, Dict
from fastapi import FastAPI, HTTPException, Response
from src.core.models import Item
from src.core.storage_interface import StorageInterface

app = FastAPI(
    title="Flexible CRUD API",
    description="A demonstration API for CRUD operations with configurable storage backends.",
    version="1.0.0",
)

storage_adapter: Optional[StorageInterface] = None # Allow it to be None initially

@app.post("/items", response_model=Item, tags=["Items"],
          summary="Create a new item",
          description="Creates a new item in the configured storage backend. The item ID is generated by the storage backend.")
async def create_item(item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=500, detail="Storage adapter not initialized")
    # Pydantic v2 uses model_dump, v1 uses dict. item.id is optional.
    # Exclude 'id' if present, as storage should generate/confirm it.
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    created_item_dict = await storage_adapter.create(item_data)
    return Item(**created_item_dict)

@app.get("/items", response_model=List[Item], tags=["Items"],
         summary="Read all items",
         description="Retrieves a list of all items currently stored in the backend.")
async def read_items() -> List[Item]:
    if storage_adapter is None:
        raise HTTPException(status_code=500, detail="Storage adapter not initialized")
    items_dict_list = await storage_adapter.read_all()
    return [Item(**item_dict) for item_dict in items_dict_list]

@app.get("/items/{item_id}", response_model=Item, tags=["Items"],
          summary="Read a specific item by ID",
          description="Retrieves a single item by its unique ID.")
async def read_item(item_id: str) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=500, detail="Storage adapter not initialized")
    item_dict = await storage_adapter.read_one(item_id)
    if item_dict is None:
        raise HTTPException(status_code=404, detail="Item not found")
    return Item(**item_dict)

@app.put("/items/{item_id}", response_model=Item, tags=["Items"],
         summary="Update an existing item",
         description="Updates the details of an existing item, identified by its ID. All fields provided in the request body will be updated.")
async def update_item(item_id: str, item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=500, detail="Storage adapter not initialized")
    # Exclude 'id' from the payload to prevent attempts to change the item's ID via the body.
    # The item_id from the path is the canonical one.
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    updated_item_dict = await storage_adapter.update(item_id, item_data)
    if updated_item_dict is None:
        raise HTTPException(status_code=404, detail="Item not found")
    return Item(**updated_item_dict)

@app.delete("/items/{item_id}", status_code=204, tags=["Items"],
            summary="Delete an item",
            description="Deletes an item from the storage backend using its ID. Returns a 204 No Content response on successful deletion.")
async def delete_item(item_id: str):
    if storage_adapter is None:
        raise HTTPException(status_code=500, detail="Storage adapter not initialized")
    deleted = await storage_adapter.delete(item_id)
    if not deleted:
        raise HTTPException(status_code=404, detail="Item not found")
    return Response(status_code=204)
