from typing import List, Optional, Dict # Keep Dict if still used elsewhere
from fastapi import FastAPI, HTTPException, Response, Query # Query added
from src.core.models import Item, PaginatedResponseModel # PaginatedResponseModel added
from src.core.storage_interface import StorageInterface, PaginatedDbResponse # PaginatedDbResponse for type hint

app = FastAPI(
    title="Flexible CRUD API",
    description="A demonstration API for CRUD operations with configurable storage backends.",
    version="1.0.0",
)

storage_adapter: Optional[StorageInterface] = None # Allow it to be None initially

@app.post("/items", response_model=Item, tags=["Items"],
          summary="Create a new item",
          description="Creates a new item in the configured storage backend. The item ID is generated by the storage backend.")
async def create_item(item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    try:
        created_item_dict = await storage_adapter.create(item_data)
        return Item(**created_item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred during item creation: {e}")


@app.get(
    "/items",
    response_model=PaginatedResponseModel[Item], # Use the new generic Pydantic model
    summary="Read all items with pagination",
    tags=["Items"],
    description="Retrieves a list of items with pagination. Allows specifying offset and limit for controlling the result set."
)
async def read_items(
    offset: int = Query(0, ge=0, description="Offset for pagination. Number of items to skip from the beginning. Must be non-negative."),
    limit: int = Query(10, gt=0, le=100, description="Limit for pagination. Maximum number of items to return. Must be positive and at most 100.")
):
    if storage_adapter is None:
        # Use 503 Service Unavailable if the storage isn't ready
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")

    try:
        # Call the storage adapter's read_all method which returns PaginatedDbResponse (TypedDict)
        paginated_db_data: PaginatedDbResponse = await storage_adapter.read_all(offset=offset, limit=limit)

        # Convert the list of dictionaries (items) from the DB response
        # to a list of Item Pydantic models. This also validates each item.
        validated_items = [Item(**item_dict) for item_dict in paginated_db_data["items"]]

        # Construct the final response using the PaginatedResponseModel Pydantic model.
        # This ensures the overall response structure is also validated and correctly serialized.
        return PaginatedResponseModel[Item](
            items=validated_items,
            total_count=paginated_db_data["total_count"],
            offset=paginated_db_data["offset"],
            limit=paginated_db_data["limit"]
        )
    except RuntimeError as e: # Catch custom errors from adapters (e.g., "Error reading items from...")
        # Log e for debugging if necessary (e.g., print(f"Adapter error in read_items: {e}"))
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e: # Catch any other unexpected errors during the process
        # Log e for debugging (e.g., print(f"Unexpected error in read_items: {e}") or proper logging)
        raise HTTPException(status_code=500, detail="An unexpected error occurred while retrieving items.")


@app.get("/items/{item_id}", response_model=Item, tags=["Items"],
          summary="Read a specific item by ID",
          description="Retrieves a single item by its unique ID.")
async def read_item(item_id: str) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    try:
        item_dict = await storage_adapter.read_one(item_id)
        if item_dict is None:
            raise HTTPException(status_code=404, detail="Item not found")
        return Item(**item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while retrieving item {item_id}: {e}")


@app.put("/items/{item_id}", response_model=Item, tags=["Items"],
         summary="Update an existing item",
         description="Updates the details of an existing item, identified by its ID. All fields provided in the request body will be updated.")
async def update_item(item_id: str, item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    try:
        updated_item_dict = await storage_adapter.update(item_id, item_data)
        if updated_item_dict is None:
            raise HTTPException(status_code=404, detail="Item not found")
        return Item(**updated_item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while updating item {item_id}: {e}")


@app.delete("/items/{item_id}", status_code=204, tags=["Items"],
            summary="Delete an item",
            description="Deletes an item from the storage backend using its ID. Returns a 204 No Content response on successful deletion.")
async def delete_item(item_id: str):
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    try:
        deleted = await storage_adapter.delete(item_id)
        if not deleted:
            raise HTTPException(status_code=404, detail="Item not found")
        return Response(status_code=204)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while deleting item {item_id}: {e}")
