from typing import List, Optional, Dict # Keep Dict if still used elsewhere
from fastapi import FastAPI, HTTPException, Response, Query # Query added
from src.core.models import Item, PaginatedResponseModel # PaginatedResponseModel added
from src.core.storage_interface import StorageInterface, PaginatedDbResponse # PaginatedDbResponse for type hint

# Define tags for OpenAPI documentation
tags_metadata = [
    {
        "name": "Items",
        "description": "CRUD operations for individual items, including paginated listing.",
    },
    {
        "name": "Items Batch Operations",
        "description": "Batch create and export operations for items.",
    },
]

app = FastAPI(
    title="Flexible CRUD API",
    description="A demonstration API for CRUD operations with configurable storage backends.",
    version="1.0.0",
    openapi_tags=tags_metadata, # Add tags metadata
)

storage_adapter: Optional[StorageInterface] = None # Allow it to be None initially

@app.post("/items", response_model=Item, tags=["Items"],
          summary="Create a new item",
          description="Creates a new item in the configured storage backend. The item ID is generated by the storage backend.")
async def create_item(item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    try:
        created_item_dict = await storage_adapter.create(item_data)
        return Item(**created_item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred during item creation: {e}")


@app.get(
    "/items",
    response_model=PaginatedResponseModel[Item],
    summary="Read all items with pagination",
    tags=["Items"],
    description="Retrieves a list of items with pagination. Allows specifying offset and limit for controlling the result set."
)
async def read_items(
    offset: int = Query(0, ge=0, description="Offset for pagination. Number of items to skip from the beginning. Must be non-negative."),
    limit: int = Query(10, gt=0, le=100, description="Limit for pagination. Maximum number of items to return. Must be positive and at most 100.")
):
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")

    try:
        paginated_db_data: PaginatedDbResponse = await storage_adapter.read_all(offset=offset, limit=limit)
        validated_items = [Item(**item_dict) for item_dict in paginated_db_data["items"]]

        return PaginatedResponseModel[Item](
            items=validated_items,
            total_count=paginated_db_data["total_count"],
            offset=paginated_db_data["offset"],
            limit=paginated_db_data["limit"]
        )
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail="An unexpected error occurred while retrieving items.")


@app.get("/items/{item_id}", response_model=Item, tags=["Items"],
          summary="Read a specific item by ID",
          description="Retrieves a single item by its unique ID.")
async def read_item(item_id: str) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    try:
        item_dict = await storage_adapter.read_one(item_id)
        if item_dict is None:
            raise HTTPException(status_code=404, detail="Item not found")
        return Item(**item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while retrieving item {item_id}: {e}")


@app.put("/items/{item_id}", response_model=Item, tags=["Items"],
         summary="Update an existing item",
         description="Updates the details of an existing item, identified by its ID. All fields provided in the request body will be updated.")
async def update_item(item_id: str, item: Item) -> Item:
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    item_data = item.model_dump(exclude_unset=True, exclude={'id'})
    try:
        updated_item_dict = await storage_adapter.update(item_id, item_data)
        if updated_item_dict is None:
            raise HTTPException(status_code=404, detail="Item not found")
        return Item(**updated_item_dict)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while updating item {item_id}: {e}")


@app.delete("/items/{item_id}", status_code=204, tags=["Items"],
            summary="Delete an item",
            description="Deletes an item from the storage backend using its ID. Returns a 204 No Content response on successful deletion.")
async def delete_item(item_id: str):
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")
    try:
        deleted = await storage_adapter.delete(item_id)
        if not deleted:
            raise HTTPException(status_code=404, detail="Item not found")
        return Response(status_code=204)
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred while deleting item {item_id}: {e}")

# --- New Batch Operations ---

@app.post(
    "/items/batch",
    response_model=List[Item],
    summary="Create multiple items in batch",
    tags=["Items Batch Operations"],
    description="Allows creating multiple items in a single request. Each item in the request list is processed. Returns a list of created items."
)
async def create_items_batch(items_to_create: List[Item]):
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")

    if not items_to_create: # Check if the input list is empty
        raise HTTPException(status_code=400, detail="No items provided for batch creation.")

    try:
        # Convert Pydantic Item models to dictionaries.
        # exclude_none=True: if a field in Item model is Optional and not provided, it won't be in the dict.
        # Adapters should handle potentially missing optional fields (e.g. 'description').
        # 'id' is Optional in Item model; if present, adapter might use it, otherwise adapter generates one.
        item_data_list = [item.model_dump(exclude_none=True) for item in items_to_create]

        created_item_dicts = await storage_adapter.create_many(item_data_list)

        # Convert list of dicts from adapter back to Item Pydantic models for response validation
        response_items = [Item(**item_dict) for item_dict in created_item_dicts]

        return response_items
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred during batch creation: {str(e)}")

@app.get(
    "/items/export",
    response_model=List[Item],
    summary="Export all items from storage",
    tags=["Items Batch Operations"],
    description="Retrieves all items currently stored in the backend without pagination. Use with caution on very large datasets."
)
async def export_all_items():
    if storage_adapter is None:
        raise HTTPException(status_code=503, detail="Storage adapter not initialized. Please check configuration.")

    try:
        exported_item_dicts = await storage_adapter.export_all()

        response_items = [Item(**item_dict) for item_dict in exported_item_dicts]

        return response_items
    except RuntimeError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"An unexpected error occurred during export: {str(e)}")
