"""
Defines the abstract base class (interface) for all storage adapters.

This interface ensures that any storage backend implementation will provide a consistent
set of asynchronous CRUD (Create, Read, Update, Delete) operations for items,
as well as batch creation and export functionalities.
Items are represented as dictionaries.
"""
from abc import ABC, abstractmethod
from typing import TypedDict, List, Dict, Any, Optional

# Definition for the paginated response structure
class PaginatedDbResponse(TypedDict):
    items: List[Dict[str, Any]]
    total_count: int
    offset: int
    limit: int

class StorageInterface(ABC):
    """
    Abstract base class defining the contract for storage adapter implementations.
    All methods are asynchronous.
    """

    @abstractmethod
    async def create(self, item_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Creates a new item in the storage.

        Args:
            item_data: A dictionary containing the data for the new item.
                       The 'id' may or may not be present; the implementation
                       is responsible for generating an ID if not provided or
                       if the provided ID needs to be overridden.

        Returns:
            A dictionary representing the created item, including its final ID.
        """
        pass

    @abstractmethod
    async def read_all(self, offset: int = 0, limit: int = 100) -> PaginatedDbResponse:
        """
        Retrieves items from the storage with pagination.

        Args:
            offset: The number of items to skip before starting to collect the result set.
            limit: The maximum number of items to return.

        Returns:
            A dictionary conforming to PaginatedDbResponse, containing the list of
            items for the current page, total count of items in storage,
            the offset used, and the limit used.
            Returns an empty list of items if no items are found for the given page,
            but total_count should still reflect the overall count in storage.
        """
        pass

    @abstractmethod
    async def read_one(self, item_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieves a single item by its ID.

        Args:
            item_id: The unique identifier of the item to retrieve.

        Returns:
            A dictionary representing the found item, or None if no item
            with the given ID exists.
        """
        pass

    @abstractmethod
    async def update(self, item_id: str, item_data: Dict[str, Any]) -> Optional[Dict[str, Any]]:
        """
        Updates an existing item identified by its ID.

        Args:
            item_id: The ID of the item to update.
            item_data: A dictionary containing the new data for the item.
                       This dictionary may contain all or a subset of item fields.
                       The 'id' field in item_data, if present, should be ignored
                       or validated against item_id.

        Returns:
            A dictionary representing the updated item, or None if no item
            with the given ID was found.
        """
        pass

    @abstractmethod
    async def delete(self, item_id: str) -> bool:
        """
        Deletes an item from the storage by its ID.

        Args:
            item_id: The ID of the item to delete.

        Returns:
            True if the item was successfully deleted, False otherwise (e.g., if
            the item was not found).
        """
        pass

    @abstractmethod
    async def create_many(self, items_data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Creates multiple items in batch.

        Args:
            items_data: A list of dictionaries, where each dictionary contains
                        the data for an item to be created. IDs are typically
                        generated by the storage backend if not provided or if
                        they need to be overridden.

        Returns:
            A list of dictionaries, where each dictionary represents a
            created item, now including its server-assigned ID. The order
            of returned items should correspond to the order of items in
            the input list if possible, but is not strictly guaranteed
            unless specified by the implementing adapter.
        """
        pass

    @abstractmethod
    async def export_all(self) -> List[Dict[str, Any]]:
        """
        Exports all items from the storage without pagination.

        Warning: This method can be resource-intensive for large datasets.
        It's intended for scenarios like data backup or full data transfers
        where pagination is not suitable.

        Returns:
            A list of dictionaries, where each dictionary represents an item.
            Returns an empty list if no items are found.
        """
        pass
